Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g36, pull requests merged in 2024-11, with the labels that each got.

#106 Collaboration service frontend
  frontend/package.json
  frontend/src/components/collaboration-service/AceEditorThemes.ts
  frontend/src/components/collaboration-service/CodeEditingArea.tsx
  frontend/src/components/collaboration-service/CodeEditorSettings.ts
  frontend/src/components/collaboration-service/LanguageSelectionButton.tsx
  frontend/src/components/collaboration-service/LayoutManager.tsx
  frontend/src/components/collaboration-service/ProgrammingLanguages.ts
  frontend/src/components/collaboration-service/QuestionArea.tsx
  frontend/src/components/collaboration-service/TextEditor.tsx
  frontend/src/components/common/VerticallySplitedView.tsx
  frontend/src/contexts/CollaborationContext.tsx
  frontend/src/pages/collaboration-service/CollaborationPage.tsx
  frontend/yarn.lock
Labels: frontend, collab-service

#113 [Nice-to-have N1] Chat feature (and bug fixes in collaboration service frontend)
  collaboration-service/server.ts
  frontend/src/components/collaboration-service/ChatBubble.tsx
  frontend/src/components/collaboration-service/ChattingOverlay.tsx
  frontend/src/components/collaboration-service/CodeEditingArea.tsx
  frontend/src/components/collaboration-service/CodeEditorSettings.ts
  frontend/src/components/collaboration-service/LayoutManager.tsx
  frontend/src/components/collaboration-service/QuestionArea.tsx
  frontend/src/components/common/VerticallySplitView.tsx
  frontend/src/contexts/CollaborationContext.tsx
  frontend/src/pages/collaboration-service/CollaborationPage.tsx
Labels: frontend, backend, collab-service, nice-to-have

#120 N2 history system
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/user-service/UserService.ts
  frontend/src/components/common/PageHeader.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/sheet.tsx
  frontend/src/components/ui/sidebar.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/hooks/use-mobile.tsx
  frontend/src/lib/utils.ts
  frontend/src/pages/AttemptedHistoryPage.tsx
  frontend/src/pages/collaboration-service/CollaborationPage.tsx
  frontend/src/pages/question-service/ListQuestionPage.tsx
  frontend/src/pages/question-service/ViewQuestionPage.tsx
  frontend/tailwind.config.js
  frontend/yarn.lock
  user-service/src/controllers/authController.ts
  user-service/src/controllers/userController.ts
  user-service/src/models/attemptHistoryModel.ts
  user-service/src/models/userModel.ts
  user-service/src/routes/userRoute.ts
Labels: nice-to-have

#130 Change the default theme of the code editor
  frontend/src/components/collaboration-service/AceEditorThemes.ts
  frontend/src/components/collaboration-service/CodeEditingArea.tsx
Labels: enhancement, frontend, collab-service

#131 Remove development message in login page and redundant asset folder
  frontend/src/assets/react.svg
  frontend/src/pages/user-service/LoginPage.tsx
Labels: frontend, user-service

#133 Fix bug where user's attempted code is not reflected in ViewQuestionPage
  frontend/src/App.tsx
  frontend/src/pages/AttemptedHistoryPage.tsx
  frontend/src/pages/question-service/ViewQuestionPage.tsx
Labels: bug

#137 Fix some messaging + AI NTH bugs
  collaboration-service/server.ts
  collaboration-service/src/chat/chatbotController.ts
  frontend/src/components/collaboration-service/communication/ChatBubble.tsx
  frontend/src/components/collaboration-service/communication/ChatPanel.tsx
  frontend/src/components/collaboration-service/communication/ChattingOverlay.tsx
  frontend/src/components/common/CustomMarkdown.tsx
  frontend/src/lib/utils.ts
Labels: bug

#141 Fix login checking bug and add retry system for login checking
  frontend/src/api/user-service/UserService.ts
  frontend/src/contexts/AuthContext.tsx
Labels: bug

#118 [Nice to have] Kubernetes deployment and horizontal scaling
  collaboration-service/.gitattributes
  collaboration-service/Dockerfile
  collaboration-service/config.ts
  collaboration-service/src/kafka/collabController.ts
  collaboration-service/wait_for_kafka.sh
  frontend/yarn.lock
  k8s/collaboration-claim1-persistentvolumeclaim.yaml
  k8s/collaboration-cm0-configmap.yaml
  k8s/collaboration-deployment.yaml
  k8s/collaboration-service.yaml
  k8s/frontend-claim1-persistentvolumeclaim.yaml
  k8s/frontend-cm0-configmap.yaml
  k8s/frontend-deployment.yaml
  k8s/frontend-service.yaml
  k8s/kafka-deployment.yaml
  k8s/kafka-service.yaml
  k8s/matching-claim1-persistentvolumeclaim.yaml
  k8s/matching-cm0-configmap.yaml
  k8s/matching-deployment.yaml
  k8s/matching-service.yaml
  k8s/question-claim1-persistentvolumeclaim.yaml
  k8s/question-cm0-configmap.yaml
  k8s/question-deployment.yaml
  k8s/question-service.yaml
  k8s/user-claim1-persistentvolumeclaim.yaml
  k8s/user-cm0-configmap.yaml
  k8s/user-deployment.yaml
  k8s/user-service.yaml
  k8s/zookeeper-deployment.yaml
  k8s/zookeeper-service.yaml
  matching-service/.gitattributes
  matching-service/Dockerfile
  matching-service/wait_for_kafka.sh
  metrics-server/metrics-server.yaml
  question-service/Dockerfile
  question-service/package-lock.json
  user-service/Dockerfile
  user-service/package-lock.json
Labels: nice-to-have
